### PR TITLE
Added content downloader & unlink memory card options

### PR DESCRIPTION
**Pull request by yifanlu**
This adds the Content Downloader (from IDU mode) and Unlink Memory Card (to use a card linked with another account or higher firmware).

We need translations (_only_) for the following languages:
- [x] Japanese
- [x] French
- [x] Spanish
- [x] German
- [x] Italian
- [x] Dutch
- [x] Portuguese PT
- [x] Portuguese BR
- [x] Russian
- [x] Korean
- [x] Chinese traditional
- [x] Chinese simplified
- [x] Finnish
- [x] Swedish
- [ ] Danish
- [x] Norwegian
- [x] Polish
- [x] Turkish

For the following strings:

|Description|String to Translate|
|-----------|-------------------|
|Setting option to download DRM-free packages|`"Content Downloader"`|
|Setting option to remove MC lock on an account/firmware|`"Unlink Memory Card"`|
|Success message for unlinking|`"ux0:id.dat has been deleted. This memory card can now be used on any Vita."`|
|Failure message for unlinking (when memory card is not inserted)|`"Failed to mount ux0. Is a memory card inserted?"`|

If a language is already taken by another commenter, please give it a thumbs up if you think it is good. If you think it can be improved, give it a thumbs down and add your own translation in a new comment.

### CODE REVIEW

**Comment by GrayJack** [comment]
Portuguese BR

"Baixar Conteúdo"
"Desassociar o Cartão de Memória"
"ux0:id.dat foi deletado. Agora este cartão de memória pode ser usado em qualquer Vita."
"Falha ao montar ux0. O cartão de memória está inserido?"

**Comment by francl35** [comment]
French translation :
"Content Downloader" : Téléchargement de contenu
"Unlink Memory Card" : Supprimer lien carte mémoire 
"ux0:id.dat has been deleted. This memory card can now be used on any Vita." : ux0:id.dat a été supprimé. Cette carte mémoire peut être utilisée sur n'importe quelle Vita.
"Failed to mount ux0. Is a memory card inserted?" : Le montage de ux0 a échoué. Y a-t-il une carte mémoire insérée ?

**Comment by WZ-JK** [comment]
Translation to Spanish:

"Descargador de Contenido"
"Desvincular la Tarjeta de Memoria"
"El ux0:id.dat ha sido eliminado. Esta tarjeta de memoria ahora se puede utilizar en cualquier Vita."
"Ha habido un fallo al montar el ux0. ¿Se ha insertado una tarjeta de memoria?"

**Comment by Rufis01** [comment]
Italian translation :
"Content Downloader" : Scarica contenuto
"Unlink Memory Card" : Disassocia Memory Card
"ux0:id.dat has been deleted. This memory card can now be used on any Vita." : ux0:id.dat è stato cancellato. Adesso questa Memory Card può essere usata su qualsiasi PS Vita. 
"Failed to mount ux0. Is a memory card inserted?" : Impossibile montare ux0. La Memory Card è  inserita?

**Comment by kirisame0017** [comment]
> "コンテンツ ダウンローダー"

> "メモリーカードとのリンクを切断する"

> "ux0:id.datが削除されました。このメモリーカードはそのこのVita以外で使用することが出来ます。"

> "ux0のマウントに失敗しました。メモリーカードは挿入されていますか？"

**Comment by Marcely1199** [comment]
"Inhalt Downloader" (Content Downloader sounds better)
"Memory Stick entkoppeln"
"ux0:id.dat wurde entfernt. Dieses Hi Memory Stick kann nun auf jeder PSVita verwendet werden."
"Verbindung mit ux0 ist fehlgeschlagen. Ist ein Memory Stick angeschlossen?"

**Comment by Marcely1199** [comment]
^
German

**Comment by jja2000** [comment]
Dutch Translation:
"Inhoud downloader"
"Memory Card loskoppelen"
"ux0:id.dat is verwijderd. Deze Memory Card kan nu op elke Vita gebruikt worden."
"Aankoppelen van ux0 is mislukt. Is er wel een Memory Stick aanwezig?"

**Comment by magpte** [comment]
Chinese traditional
“下載內容管理器”
“記憶卡關聯解除”
“ux0的id.dat已經刪除，這張記憶卡現在可以應用到任意PSV上”
“載入ux0失敗，請檢查記憶卡是否已經插入”

Chinese simplified
“下载内容管理器”
“存储卡关联解除”
“ux0的id.dat已经删除，这张存储卡现在可以用在任意PSV上”
“载入ux0失败，请检查存储卡是否已经插入”

**Comment by TriggerHavoc** [comment]
Korean
"Content Downloader" -> "컨텐츠 다운로더"

"Unlink Memory Card" -> "메모리 카드 언링크"

"ux0:id.dat has been deleted. This memory card can now be used on any Vita."
-> "ux0:id.dat 파일이 삭제되었습니다. 이제 이 메모리 카드는 모든 비타에서 사용하실 수 있습니다."

"Failed to mount ux0. Is a memory card inserted?"
-> "ux0에 마운트 할 수 없습니다. 메모리 카드가 올바르게 삽입되어 있습니까?"

**Comment by dec0dOS** [comment]
Russian Translation:
"Загрузчик контента"
"Отвязать карту памяти"
"ux0:id.dat был удален. Эта карта памяти теперь может быть использована на любой PSVita."
"Ошибка при монтировании ux0. Проверьте, вставлена ли карта памяти"

**Comment by Jefphar** [comment]
Filipino/Tagalog Translation: ux0:id.dat has been deleted. This memory card can now be used on any Vita." : "duo:id.dat ay nabura na.Pwede ng gamitin ang memoryang baraha sa kahit anong vita.

**Comment by Makein** [comment]
Russian Translation:

"Content Downloader" -> "Загрузчик контента"

"Unlink Memory Card" -> "Отвязать карту памяти"

"ux0:id.dat has been deleted. This memory card can now be used on any Vita."
-> "ux0:id.dat был удален. Теперь эту карту памяти можно использовать с любой Vita/TV консолью."

"Failed to mount ux0. Is a memory card inserted?"
-> "Ошибка при монтировании ux0. Вставлена ли карта памяти?"

**Comment by Chronicl3** [comment]
Turkish Translation :
"Content Downloader" -> "İçerik İndiricisi
"Unlink Memory Card" -> "Hafıza Kartı Bağlantısını Kaldır"
"ux0:id.dat has been deleted. This memory card can now be used on any Vita."
->ux0:id.dat silindi.Bu hafıza kartı şuan herhangi bir vita da kullanılabilir"
"Failed to mount ux0. Is a memory card inserted?"
->"ux0 dizin okuma başarısız oldu.Hafıza kartınız takılı mı?"

**Comment by salohut** [comment]
Swedish translation:

"Content Downloader":
Innehålls-nerladdare

"Unlink Memory Card":
Av-länka minneskort

"ux0:id.dat has been deleted. This memory card can now be used on any Vita.":
ux0:id.dat har raderats. Det här minneskortet kan nu användas i vilken Vita som helst. 

"Failed to mount ux0. Is a memory card inserted?":
Fel vid montering av ux0. Har du satt i ett minneskort?

**Comment by Promises** [comment]
Norwegian translation:

"Content Downloader":
Innholds Nedlaster

"Unlink Memory Card":
Lås opp Minnekort

"ux0:id.dat has been deleted. This memory card can now be used on any Vita.":
ux0:id.dat er slettet. Dette minnekortet kan brukest på hvilken som helst Vita.

"Failed to mount ux0. Is a memory card inserted?":
Klarte ikkje montere av ux0. Har du satt i eit minnekort?

**Comment by Wassburgare** [comment]
Swedish translation (based on salohut's translation):

"Content Downloader":
Innehållsnedladdare

"Unlink Memory Card":
Avlänka minneskort

"ux0:id.dat has been deleted. This memory card can now be used on any Vita.":
ux0:id.dat har tagits bort. Det här minneskortet kan nu användas i valfri Vita.

"Failed to mount ux0. Is a memory card inserted?":
Misslyckades med att montera ux0. Har du satt i ett minneskort?

**Comment by fayer3** [comment]
German (based on Marcely1199's translation)
"Inhalt Downloader" 
"Speicherkarte entkoppeln"
"ux0:id.dat wurde entfernt. Diese Speicherkarte kann nun auf jeder PSVita verwendet werden."
"Mounten von ux0 ist fehlgeschlagen. Ist eine Speicherkarte eingesteckt?"

**Comment by hoshiraku** [comment]
"Content Downloader":
内容下载器

"Unlink Memory Card"：
取消记忆卡关联

"ux0:id.dat has been deleted. This memory card can now be used on any Vita."
ux0:id.dat已经被删除。这个记忆卡能被用于任意Vita

"Failed to mount ux0. Is a memory card inserted?"
ux0装载失败。是否插入了记忆卡？

**Comment by hoshiraku** [comment]
Japanese:
"コンテンツのダウンローダー"
"メモリーカードをアンリンクする
"ux0:id.datが削除されました。このメモリーカードはどのVitaでも使用できるようになりました。"
"ux0のマウントに失敗しました。メモリーカードは入れていますか？"

**Comment by niszczycielnpc** [comment]
Polish PL

"Pobieranie Content"
"Odłącz kartę Memory Card"
"ux0:id.dat został usunięty z karty. Można jej teraz używać w każdym systemie Vita"
"Nie można odczytać karty, Czy karta jest włożona?"

**Comment by UltiNaruto** [comment]
Small fix for @francl35 translation for "Unlink memory card" you can say "Délier la carte mémoire" which sounds better than "Supprimer lien carte mémoire". It's robotic language xD

**Comment by szczuru** [comment]
@niszczycielnpc,

Pobieranie Content? :O why didn't you translate content? According to CMA in polish language it should be:
"Pobieranie zawartości".

**Comment by poppamies** [comment]
Finnish translation:

"Sisällönlataaja"
"Irrota muistikortti"
"ux0:id.dat on poistettu. Voit nyt käyttää tätä muistikorttia millä tahansa Vitalla."
"ux0:n liittäminen epäonnistui. Onko muistikortti laitteessa?"

**Comment by bosshunter** [comment]
Portuguese PT translation:

"Descarregar Conteúdo"
"Desassociar Cartão de Memória"
"ux0:id.dat foi eliminado. Este cartão de memória pode agora ser usado em qualquer Vita."
"Falha ao montar ux0. O cartão de memória está inserido?"

**Comment by Ziusun** [comment]
German

"Content Downloader" - Inhaltsdownloader

"Unlink Memory Card" - Speicherkarte entkoppeln

"ux0:id.dat has been deleted. This memory card can now be used on any Vita." - Der Dateieintrag ux0:id.dat wurde gelöscht. Diese Speicherkarte kann jetzt mit jeder Playstation Vita verwendet werden.

"Failed to mount ux0. Is a memory card inserted?" - Die Partition ux0: konnte nicht gemountet werden. Ist eine Speicherkarte eingesteckt?

**Comment by yifanlu** [comment]
If nobody translates Danish in the next three hours, I will use google translate.

**Comment by 2dook** [comment]
Improvement for Dutch translation: 

Instead of saying Memory Card and Memory stick even though they have their respective dutch translation is not smart.
I'd rather go for Geheugenkaart - which when translated literally means memory card.

"Inhoud downloader" - Good.
"Memory Card loskoppelen" - Good, but replace Memory Card with "Geheugenkaart".
"ux0:id.dat is verwijderd. Deze Memory Card kan nu op elke Vita gebruikt worden." - Good, replace Memory Card with "Geheugenkaart".
"Aankoppelen van ux0 is mislukt. Is er wel een Memory Stick aanwezig?" - Here you used Memory Stick, even though english translation states you need to translate Memory Card, which then translates into "Geheugenkaart"

**Comment by ahmad766667** [comment]
"بارگیری محتوا"
"جدا کردن کارت حافظه"
"فایلux0:id.datپاک شده.در حال حاظر این کارت حافظه بر روی هر ویتایی قابل استفاده است"
"اتصال ux0 با خطا روبرو شده.آیا کارت حافظه در دستگاه قرار دارد؟"

**Comment by yifanlu** [comment]
> We need translations (only) for the following languages

**Pull request merged**
